docker-compose-yaml: docker-compose.yml

project: demo-poly-2023-us2-aws

# The ssh and api settings are needed to configure Lagoon outside of amazeeio.cloud infrastructure
# ssh: ssh.amazeeio.cloud:32222
# api: https://api.amazeeio.cloud/graphql

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    - run:
        name: IF no Drupal installed and we are on a main branch, but not of the dev project
        command: |
            if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ] && [ "$LAGOON_GIT_BRANCH" == "main" ] && [ "$LAGOON_PROJECT" != "demo-base-poly-2023-uk3-aws" ]; then
                # no drupal installed, sync DB from archive backup
                drush -y archive:restore --files --db ./poly/archive.tar.gz
                drush -y cr
            fi
        service: cli
        shell: bash
    - run:
        name: IF no Drupal installed and we are on a dev branch
        command: |
            if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ] && [ "$LAGOON_GIT_BRANCH" == "dev" ]; then
                # no drupal installed, sync DB from archive backup
                drush -y archive:restore --files --db ./poly/archive.tar.gz
                drush -y cr
            fi
        service: cli
        shell: bash
    # Enable once config sync has been setup.
    - run:
       name: drush cim
       command: drush -y cim
       service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  main:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/30 * * * *"
        command: drush cron
        service: cli
