#!/bin/bash

PROJECT="demo-poly-2023-ch4-gcp"
# PROJECT="demo-poly-2023-us2-aws"
# PROJECT="demo-poly-2023-us3-gcp"
# PROJECT="demo-poly-2023-de3-aws"
# PROJECT="demo-poly-2023-fi2-gcp"
echo "Project: $PROJECT" 

LAGOON_KEY=`lagoon get project-key -p $PROJECT | tail -n 1` 
echo $LAGOON_KEY > /tmp/lagoon-polykeypub.aio 
echo "Key: $LAGOON_KEY" 

gh repo deploy-key add /tmp/lagoon-polykeypub.aio
