#!/bin/bash

PROJECTA="demo-poly-2023-de3-aws"
PROJECTB="demo-poly-2023-fi2-gcp"


lagoon --force deploy branch -b main -e main -p $PROJECTA
echo "Triggered deploy of $PROJECTA"
echo ""

lagoon --force deploy branch -b main -e main -p $PROJECTB
echo "Triggered deploy of $PROJECTB"
echo ""
