#!/bin/bash

PROJECTA="demo-poly-2023-ch4-gcp"
PROJECTB="demo-poly-2023-us2-aws"
PROJECTC="demo-poly-2023-us3-gcp"
PROJECTD="demo-poly-2023-de3-aws"
PROJECTE="demo-poly-2023-fi2-gcp"

STATUSA="loading..."
STATUSB="loading..."
STATUSC="loading..."
STATUSD="loading..."
STATUSE="loading..."

while [ 1 -gt 0 ]; do
  clear

  echo $PROJECTA\t $STATUSA
  echo $PROJECTB\t $STATUSB
  echo $PROJECTC\t $STATUSC
  echo $PROJECTD\t $STATUSD
  echo $PROJECTE\t $STATUSE

  STATUSA=`lagoon list deployments -p $PROJECTA -e main | head -n 2 | tail -n 1 | awk '{print $4}'`
  STATUSB=`lagoon list deployments -p $PROJECTB -e main | head -n 2 | tail -n 1 | awk '{print $4}'`
  STATUSC=`lagoon list deployments -p $PROJECTC -e main | head -n 2 | tail -n 1 | awk '{print $4}'`
  STATUSD=`lagoon list deployments -p $PROJECTD -e main | head -n 2 | tail -n 1 | awk '{print $4}'`
  STATUSE=`lagoon list deployments -p $PROJECTE -e main | head -n 2 | tail -n 1 | awk '{print $4}'`
done;
